// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/plugin/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MiddlewareResponse_Action int32

const (
	MiddlewareResponse_CONTINUE MiddlewareResponse_Action = 0 // Pass request through (optionally with modified headers)
	MiddlewareResponse_ABORT    MiddlewareResponse_Action = 1 // Stop request processing, return the provided response
)

// Enum value maps for MiddlewareResponse_Action.
var (
	MiddlewareResponse_Action_name = map[int32]string{
		0: "CONTINUE",
		1: "ABORT",
	}
	MiddlewareResponse_Action_value = map[string]int32{
		"CONTINUE": 0,
		"ABORT":    1,
	}
)

func (x MiddlewareResponse_Action) Enum() *MiddlewareResponse_Action {
	p := new(MiddlewareResponse_Action)
	*p = x
	return p
}

func (x MiddlewareResponse_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MiddlewareResponse_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_plugin_proto_plugin_proto_enumTypes[0].Descriptor()
}

func (MiddlewareResponse_Action) Type() protoreflect.EnumType {
	return &file_pkg_plugin_proto_plugin_proto_enumTypes[0]
}

func (x MiddlewareResponse_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MiddlewareResponse_Action.Descriptor instead.
func (MiddlewareResponse_Action) EnumDescriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{23, 0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{0}
}

type Manifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Requires      []*Dependency          `protobuf:"bytes,5,rep,name=requires,proto3" json:"requires,omitempty"`
	Permissions   []*Permission          `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Frontend      *FrontendManifest      `protobuf:"bytes,7,opt,name=frontend,proto3" json:"frontend,omitempty"` // null if backend-only
	Settings      []*SettingField        `protobuf:"bytes,8,rep,name=settings,proto3" json:"settings,omitempty"`
	Priority      int32                  `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	RateLimit     int32                  `protobuf:"varint,10,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manifest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manifest) GetRequires() []*Dependency {
	if x != nil {
		return x.Requires
	}
	return nil
}

func (x *Manifest) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Manifest) GetFrontend() *FrontendManifest {
	if x != nil {
		return x.Frontend
	}
	return nil
}

func (x *Manifest) GetSettings() []*SettingField {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Manifest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Manifest) GetRateLimit() int32 {
	if x != nil {
		return x.RateLimit
	}
	return 0
}

type Dependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Dependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Verbs         []string               `protobuf:"bytes,2,rep,name=verbs,proto3" json:"verbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Permission) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Permission) GetVerbs() []string {
	if x != nil {
		return x.Verbs
	}
	return nil
}

type FrontendManifest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RemoteEntry    string                 `protobuf:"bytes,1,opt,name=remote_entry,json=remoteEntry,proto3" json:"remote_entry,omitempty"`
	ExposedModules map[string]string      `protobuf:"bytes,2,rep,name=exposed_modules,json=exposedModules,proto3" json:"exposed_modules,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Routes         []*FrontendRoute       `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	SettingsPanel  string                 `protobuf:"bytes,4,opt,name=settings_panel,json=settingsPanel,proto3" json:"settings_panel,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FrontendManifest) Reset() {
	*x = FrontendManifest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendManifest) ProtoMessage() {}

func (x *FrontendManifest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontendManifest.ProtoReflect.Descriptor instead.
func (*FrontendManifest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *FrontendManifest) GetRemoteEntry() string {
	if x != nil {
		return x.RemoteEntry
	}
	return ""
}

func (x *FrontendManifest) GetExposedModules() map[string]string {
	if x != nil {
		return x.ExposedModules
	}
	return nil
}

func (x *FrontendManifest) GetRoutes() []*FrontendRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *FrontendManifest) GetSettingsPanel() string {
	if x != nil {
		return x.SettingsPanel
	}
	return ""
}

type FrontendRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	SidebarEntry  *SidebarEntry          `protobuf:"bytes,3,opt,name=sidebar_entry,json=sidebarEntry,proto3" json:"sidebar_entry,omitempty"` // null if no sidebar link
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontendRoute) Reset() {
	*x = FrontendRoute{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendRoute) ProtoMessage() {}

func (x *FrontendRoute) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontendRoute.ProtoReflect.Descriptor instead.
func (*FrontendRoute) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *FrontendRoute) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FrontendRoute) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *FrontendRoute) GetSidebarEntry() *SidebarEntry {
	if x != nil {
		return x.SidebarEntry
	}
	return nil
}

type SidebarEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Icon          string                 `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	Section       string                 `protobuf:"bytes,3,opt,name=section,proto3" json:"section,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidebarEntry) Reset() {
	*x = SidebarEntry{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidebarEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidebarEntry) ProtoMessage() {}

func (x *SidebarEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidebarEntry.ProtoReflect.Descriptor instead.
func (*SidebarEntry) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *SidebarEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SidebarEntry) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *SidebarEntry) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *SidebarEntry) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type SettingField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Options       []*SettingOption       `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	Required      bool                   `protobuf:"varint,7,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingField) Reset() {
	*x = SettingField{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingField) ProtoMessage() {}

func (x *SettingField) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingField.ProtoReflect.Descriptor instead.
func (*SettingField) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *SettingField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SettingField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SettingField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SettingField) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *SettingField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SettingField) GetOptions() []*SettingOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SettingField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type SettingOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingOption) Reset() {
	*x = SettingOption{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingOption) ProtoMessage() {}

func (x *SettingOption) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingOption.ProtoReflect.Descriptor instead.
func (*SettingOption) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *SettingOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SettingOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HTTPRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Method      string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path        string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers     map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	QueryParams map[string]string      `protobuf:"bytes,4,rep,name=query_params,json=queryParams,proto3" json:"query_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body        []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	// Context passed from Kite's middleware
	UserJson      string `protobuf:"bytes,6,opt,name=user_json,json=userJson,proto3" json:"user_json,omitempty"`          // JSON-serialized model.User
	ClusterName   string `protobuf:"bytes,7,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"` // Current cluster name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPRequest) Reset() {
	*x = HTTPRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequest) ProtoMessage() {}

func (x *HTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequest.ProtoReflect.Descriptor instead.
func (*HTTPRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *HTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPRequest) GetQueryParams() map[string]string {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

func (x *HTTPRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HTTPRequest) GetUserJson() string {
	if x != nil {
		return x.UserJson
	}
	return ""
}

func (x *HTTPRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

type HTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPResponse) Reset() {
	*x = HTTPResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResponse) ProtoMessage() {}

func (x *HTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResponse.ProtoReflect.Descriptor instead.
func (*HTTPResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *HTTPResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HTTPResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type AIToolList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*AIToolDef           `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIToolList) Reset() {
	*x = AIToolList{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIToolList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIToolList) ProtoMessage() {}

func (x *AIToolList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIToolList.ProtoReflect.Descriptor instead.
func (*AIToolList) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *AIToolList) GetTools() []*AIToolDef {
	if x != nil {
		return x.Tools
	}
	return nil
}

type AIToolDef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PropertiesJson string                 `protobuf:"bytes,3,opt,name=properties_json,json=propertiesJson,proto3" json:"properties_json,omitempty"` // JSON-encoded map[string]any (JSON Schema)
	Required       []string               `protobuf:"bytes,4,rep,name=required,proto3" json:"required,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AIToolDef) Reset() {
	*x = AIToolDef{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIToolDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIToolDef) ProtoMessage() {}

func (x *AIToolDef) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIToolDef.ProtoReflect.Descriptor instead.
func (*AIToolDef) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *AIToolDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AIToolDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AIToolDef) GetPropertiesJson() string {
	if x != nil {
		return x.PropertiesJson
	}
	return ""
}

func (x *AIToolDef) GetRequired() []string {
	if x != nil {
		return x.Required
	}
	return nil
}

type AIToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgsJson      string                 `protobuf:"bytes,2,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"` // JSON-encoded map[string]any
	ClusterName   string                 `protobuf:"bytes,3,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	UserJson      string                 `protobuf:"bytes,4,opt,name=user_json,json=userJson,proto3" json:"user_json,omitempty"` // JSON-serialized model.User for RBAC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIToolRequest) Reset() {
	*x = AIToolRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIToolRequest) ProtoMessage() {}

func (x *AIToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIToolRequest.ProtoReflect.Descriptor instead.
func (*AIToolRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *AIToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *AIToolRequest) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

func (x *AIToolRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *AIToolRequest) GetUserJson() string {
	if x != nil {
		return x.UserJson
	}
	return ""
}

type AIToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	IsError       bool                   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIToolResponse) Reset() {
	*x = AIToolResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIToolResponse) ProtoMessage() {}

func (x *AIToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIToolResponse.ProtoReflect.Descriptor instead.
func (*AIToolResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *AIToolResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AIToolResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type AIToolAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgsJson      string                 `protobuf:"bytes,2,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	ClusterName   string                 `protobuf:"bytes,3,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	UserJson      string                 `protobuf:"bytes,4,opt,name=user_json,json=userJson,proto3" json:"user_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIToolAuthRequest) Reset() {
	*x = AIToolAuthRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIToolAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIToolAuthRequest) ProtoMessage() {}

func (x *AIToolAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIToolAuthRequest.ProtoReflect.Descriptor instead.
func (*AIToolAuthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *AIToolAuthRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *AIToolAuthRequest) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

func (x *AIToolAuthRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *AIToolAuthRequest) GetUserJson() string {
	if x != nil {
		return x.UserJson
	}
	return ""
}

type AIToolAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // Empty if allowed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIToolAuthResponse) Reset() {
	*x = AIToolAuthResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIToolAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIToolAuthResponse) ProtoMessage() {}

func (x *AIToolAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIToolAuthResponse.ProtoReflect.Descriptor instead.
func (*AIToolAuthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *AIToolAuthResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *AIToolAuthResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ResourceHandlerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handlers      []*ResourceHandlerDef  `protobuf:"bytes,1,rep,name=handlers,proto3" json:"handlers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceHandlerList) Reset() {
	*x = ResourceHandlerList{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceHandlerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceHandlerList) ProtoMessage() {}

func (x *ResourceHandlerList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceHandlerList.ProtoReflect.Descriptor instead.
func (*ResourceHandlerList) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *ResourceHandlerList) GetHandlers() []*ResourceHandlerDef {
	if x != nil {
		return x.Handlers
	}
	return nil
}

type ResourceHandlerDef struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsClusterScoped bool                   `protobuf:"varint,2,opt,name=is_cluster_scoped,json=isClusterScoped,proto3" json:"is_cluster_scoped,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceHandlerDef) Reset() {
	*x = ResourceHandlerDef{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceHandlerDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceHandlerDef) ProtoMessage() {}

func (x *ResourceHandlerDef) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceHandlerDef.ProtoReflect.Descriptor instead.
func (*ResourceHandlerDef) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *ResourceHandlerDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceHandlerDef) GetIsClusterScoped() bool {
	if x != nil {
		return x.IsClusterScoped
	}
	return false
}

type ResourceRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	HandlerName string                 `protobuf:"bytes,1,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"` // Which resource handler to use
	Operation   string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`                        // "list", "get", "create", "update", "delete", "patch"
	Namespace   string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name        string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Body        []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"` // JSON/YAML body for create/update/patch
	// Context
	ClusterName   string            `protobuf:"bytes,6,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	UserJson      string            `protobuf:"bytes,7,opt,name=user_json,json=userJson,proto3" json:"user_json,omitempty"`
	QueryParams   map[string]string `protobuf:"bytes,8,rep,name=query_params,json=queryParams,proto3" json:"query_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *ResourceRequest) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

func (x *ResourceRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ResourceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ResourceRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *ResourceRequest) GetUserJson() string {
	if x != nil {
		return x.UserJson
	}
	return ""
}

func (x *ResourceRequest) GetQueryParams() map[string]string {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

type ResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"` // JSON response body
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceResponse) Reset() {
	*x = ResourceResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceResponse) ProtoMessage() {}

func (x *ResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceResponse.ProtoReflect.Descriptor instead.
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *ResourceResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ResourceResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type MiddlewareConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"` // Lower = earlier in chain
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiddlewareConfig) Reset() {
	*x = MiddlewareConfig{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlewareConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlewareConfig) ProtoMessage() {}

func (x *MiddlewareConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddlewareConfig.ProtoReflect.Descriptor instead.
func (*MiddlewareConfig) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *MiddlewareConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MiddlewareConfig) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type MiddlewareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UserJson      string                 `protobuf:"bytes,4,opt,name=user_json,json=userJson,proto3" json:"user_json,omitempty"`
	ClusterName   string                 `protobuf:"bytes,5,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiddlewareRequest) Reset() {
	*x = MiddlewareRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlewareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlewareRequest) ProtoMessage() {}

func (x *MiddlewareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddlewareRequest.ProtoReflect.Descriptor instead.
func (*MiddlewareRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *MiddlewareRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MiddlewareRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MiddlewareRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *MiddlewareRequest) GetUserJson() string {
	if x != nil {
		return x.UserJson
	}
	return ""
}

func (x *MiddlewareRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

type MiddlewareResponse struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	Action          MiddlewareResponse_Action `protobuf:"varint,1,opt,name=action,proto3,enum=kite.plugin.v1.MiddlewareResponse_Action" json:"action,omitempty"`
	ModifiedHeaders map[string]string         `protobuf:"bytes,2,rep,name=modified_headers,json=modifiedHeaders,proto3" json:"modified_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Only used with CONTINUE
	AbortStatusCode int32                     `protobuf:"varint,3,opt,name=abort_status_code,json=abortStatusCode,proto3" json:"abort_status_code,omitempty"`                                                                        // Only used with ABORT
	AbortBody       []byte                    `protobuf:"bytes,4,opt,name=abort_body,json=abortBody,proto3" json:"abort_body,omitempty"`                                                                                             // Only used with ABORT
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MiddlewareResponse) Reset() {
	*x = MiddlewareResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlewareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlewareResponse) ProtoMessage() {}

func (x *MiddlewareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddlewareResponse.ProtoReflect.Descriptor instead.
func (*MiddlewareResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *MiddlewareResponse) GetAction() MiddlewareResponse_Action {
	if x != nil {
		return x.Action
	}
	return MiddlewareResponse_CONTINUE
}

func (x *MiddlewareResponse) GetModifiedHeaders() map[string]string {
	if x != nil {
		return x.ModifiedHeaders
	}
	return nil
}

func (x *MiddlewareResponse) GetAbortStatusCode() int32 {
	if x != nil {
		return x.AbortStatusCode
	}
	return 0
}

func (x *MiddlewareResponse) GetAbortBody() []byte {
	if x != nil {
		return x.AbortBody
	}
	return nil
}

type ClusterEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "added", "removed", "updated"
	ClusterName   string                 `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterEvent) Reset() {
	*x = ClusterEvent{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterEvent) ProtoMessage() {}

func (x *ClusterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterEvent.ProtoReflect.Descriptor instead.
func (*ClusterEvent) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *ClusterEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClusterEvent) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

var File_pkg_plugin_proto_plugin_proto protoreflect.FileDescriptor

const file_pkg_plugin_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/plugin/proto/plugin.proto\x12\x0ekite.plugin.v1\"\a\n" +
	"\x05Empty\"\x9b\x03\n" +
	"\bManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x126\n" +
	"\brequires\x18\x05 \x03(\v2\x1a.kite.plugin.v1.DependencyR\brequires\x12<\n" +
	"\vpermissions\x18\x06 \x03(\v2\x1a.kite.plugin.v1.PermissionR\vpermissions\x12<\n" +
	"\bfrontend\x18\a \x01(\v2 .kite.plugin.v1.FrontendManifestR\bfrontend\x128\n" +
	"\bsettings\x18\b \x03(\v2\x1c.kite.plugin.v1.SettingFieldR\bsettings\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"rate_limit\x18\n" +
	" \x01(\x05R\trateLimit\":\n" +
	"\n" +
	"Dependency\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\">\n" +
	"\n" +
	"Permission\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x14\n" +
	"\x05verbs\x18\x02 \x03(\tR\x05verbs\"\xb5\x02\n" +
	"\x10FrontendManifest\x12!\n" +
	"\fremote_entry\x18\x01 \x01(\tR\vremoteEntry\x12]\n" +
	"\x0fexposed_modules\x18\x02 \x03(\v24.kite.plugin.v1.FrontendManifest.ExposedModulesEntryR\x0eexposedModules\x125\n" +
	"\x06routes\x18\x03 \x03(\v2\x1d.kite.plugin.v1.FrontendRouteR\x06routes\x12%\n" +
	"\x0esettings_panel\x18\x04 \x01(\tR\rsettingsPanel\x1aA\n" +
	"\x13ExposedModulesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\rFrontendRoute\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12A\n" +
	"\rsidebar_entry\x18\x03 \x01(\v2\x1c.kite.plugin.v1.SidebarEntryR\fsidebarEntry\"n\n" +
	"\fSidebarEntry\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04icon\x18\x02 \x01(\tR\x04icon\x12\x18\n" +
	"\asection\x18\x03 \x01(\tR\asection\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\"\xe8\x01\n" +
	"\fSettingField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\tR\fdefaultValue\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x127\n" +
	"\aoptions\x18\x06 \x03(\v2\x1d.kite.plugin.v1.SettingOptionR\aoptions\x12\x1a\n" +
	"\brequired\x18\a \x01(\bR\brequired\";\n" +
	"\rSettingOption\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x9e\x03\n" +
	"\vHTTPRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12B\n" +
	"\aheaders\x18\x03 \x03(\v2(.kite.plugin.v1.HTTPRequest.HeadersEntryR\aheaders\x12O\n" +
	"\fquery_params\x18\x04 \x03(\v2,.kite.plugin.v1.HTTPRequest.QueryParamsEntryR\vqueryParams\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12\x1b\n" +
	"\tuser_json\x18\x06 \x01(\tR\buserJson\x12!\n" +
	"\fcluster_name\x18\a \x01(\tR\vclusterName\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10QueryParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x01\n" +
	"\fHTTPResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12C\n" +
	"\aheaders\x18\x02 \x03(\v2).kite.plugin.v1.HTTPResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\n" +
	"AIToolList\x12/\n" +
	"\x05tools\x18\x01 \x03(\v2\x19.kite.plugin.v1.AIToolDefR\x05tools\"\x86\x01\n" +
	"\tAIToolDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0fproperties_json\x18\x03 \x01(\tR\x0epropertiesJson\x12\x1a\n" +
	"\brequired\x18\x04 \x03(\tR\brequired\"\x89\x01\n" +
	"\rAIToolRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1b\n" +
	"\targs_json\x18\x02 \x01(\tR\bargsJson\x12!\n" +
	"\fcluster_name\x18\x03 \x01(\tR\vclusterName\x12\x1b\n" +
	"\tuser_json\x18\x04 \x01(\tR\buserJson\"C\n" +
	"\x0eAIToolResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\"\x8d\x01\n" +
	"\x11AIToolAuthRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1b\n" +
	"\targs_json\x18\x02 \x01(\tR\bargsJson\x12!\n" +
	"\fcluster_name\x18\x03 \x01(\tR\vclusterName\x12\x1b\n" +
	"\tuser_json\x18\x04 \x01(\tR\buserJson\"F\n" +
	"\x12AIToolAuthResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"U\n" +
	"\x13ResourceHandlerList\x12>\n" +
	"\bhandlers\x18\x01 \x03(\v2\".kite.plugin.v1.ResourceHandlerDefR\bhandlers\"T\n" +
	"\x12ResourceHandlerDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x11is_cluster_scoped\x18\x02 \x01(\bR\x0fisClusterScoped\"\xed\x02\n" +
	"\x0fResourceRequest\x12!\n" +
	"\fhandler_name\x18\x01 \x01(\tR\vhandlerName\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12!\n" +
	"\fcluster_name\x18\x06 \x01(\tR\vclusterName\x12\x1b\n" +
	"\tuser_json\x18\a \x01(\tR\buserJson\x12S\n" +
	"\fquery_params\x18\b \x03(\v20.kite.plugin.v1.ResourceRequest.QueryParamsEntryR\vqueryParams\x1a>\n" +
	"\x10QueryParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x10ResourceResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\"H\n" +
	"\x10MiddlewareConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\"\x85\x02\n" +
	"\x11MiddlewareRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12H\n" +
	"\aheaders\x18\x03 \x03(\v2..kite.plugin.v1.MiddlewareRequest.HeadersEntryR\aheaders\x12\x1b\n" +
	"\tuser_json\x18\x04 \x01(\tR\buserJson\x12!\n" +
	"\fcluster_name\x18\x05 \x01(\tR\vclusterName\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xed\x02\n" +
	"\x12MiddlewareResponse\x12A\n" +
	"\x06action\x18\x01 \x01(\x0e2).kite.plugin.v1.MiddlewareResponse.ActionR\x06action\x12b\n" +
	"\x10modified_headers\x18\x02 \x03(\v27.kite.plugin.v1.MiddlewareResponse.ModifiedHeadersEntryR\x0fmodifiedHeaders\x12*\n" +
	"\x11abort_status_code\x18\x03 \x01(\x05R\x0fabortStatusCode\x12\x1d\n" +
	"\n" +
	"abort_body\x18\x04 \x01(\fR\tabortBody\x1aB\n" +
	"\x14ModifiedHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\x06Action\x12\f\n" +
	"\bCONTINUE\x10\x00\x12\t\n" +
	"\x05ABORT\x10\x01\"E\n" +
	"\fClusterEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\fcluster_name\x18\x02 \x01(\tR\vclusterName2\xd0\x06\n" +
	"\rPluginService\x12>\n" +
	"\vGetManifest\x12\x15.kite.plugin.v1.Empty\x1a\x18.kite.plugin.v1.Manifest\x128\n" +
	"\bShutdown\x12\x15.kite.plugin.v1.Empty\x1a\x15.kite.plugin.v1.Empty\x12E\n" +
	"\x0eOnClusterEvent\x12\x1c.kite.plugin.v1.ClusterEvent\x1a\x15.kite.plugin.v1.Empty\x12G\n" +
	"\n" +
	"HandleHTTP\x12\x1b.kite.plugin.v1.HTTPRequest\x1a\x1c.kite.plugin.v1.HTTPResponse\x12?\n" +
	"\n" +
	"GetAITools\x12\x15.kite.plugin.v1.Empty\x1a\x1a.kite.plugin.v1.AIToolList\x12N\n" +
	"\rExecuteAITool\x12\x1d.kite.plugin.v1.AIToolRequest\x1a\x1e.kite.plugin.v1.AIToolResponse\x12X\n" +
	"\x0fAuthorizeAITool\x12!.kite.plugin.v1.AIToolAuthRequest\x1a\".kite.plugin.v1.AIToolAuthResponse\x12Q\n" +
	"\x13GetResourceHandlers\x12\x15.kite.plugin.v1.Empty\x1a#.kite.plugin.v1.ResourceHandlerList\x12S\n" +
	"\x0eHandleResource\x12\x1f.kite.plugin.v1.ResourceRequest\x1a .kite.plugin.v1.ResourceResponse\x12H\n" +
	"\rGetMiddleware\x12\x15.kite.plugin.v1.Empty\x1a .kite.plugin.v1.MiddlewareConfig\x12X\n" +
	"\x0fApplyMiddleware\x12!.kite.plugin.v1.MiddlewareRequest\x1a\".kite.plugin.v1.MiddlewareResponseB)Z'github.com/zxh326/kite/pkg/plugin/protob\x06proto3"

var (
	file_pkg_plugin_proto_plugin_proto_rawDescOnce sync.Once
	file_pkg_plugin_proto_plugin_proto_rawDescData []byte
)

func file_pkg_plugin_proto_plugin_proto_rawDescGZIP() []byte {
	file_pkg_plugin_proto_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_plugin_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_plugin_proto_rawDesc), len(file_pkg_plugin_proto_plugin_proto_rawDesc)))
	})
	return file_pkg_plugin_proto_plugin_proto_rawDescData
}

var file_pkg_plugin_proto_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_plugin_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_pkg_plugin_proto_plugin_proto_goTypes = []any{
	(MiddlewareResponse_Action)(0), // 0: kite.plugin.v1.MiddlewareResponse.Action
	(*Empty)(nil),                  // 1: kite.plugin.v1.Empty
	(*Manifest)(nil),               // 2: kite.plugin.v1.Manifest
	(*Dependency)(nil),             // 3: kite.plugin.v1.Dependency
	(*Permission)(nil),             // 4: kite.plugin.v1.Permission
	(*FrontendManifest)(nil),       // 5: kite.plugin.v1.FrontendManifest
	(*FrontendRoute)(nil),          // 6: kite.plugin.v1.FrontendRoute
	(*SidebarEntry)(nil),           // 7: kite.plugin.v1.SidebarEntry
	(*SettingField)(nil),           // 8: kite.plugin.v1.SettingField
	(*SettingOption)(nil),          // 9: kite.plugin.v1.SettingOption
	(*HTTPRequest)(nil),            // 10: kite.plugin.v1.HTTPRequest
	(*HTTPResponse)(nil),           // 11: kite.plugin.v1.HTTPResponse
	(*AIToolList)(nil),             // 12: kite.plugin.v1.AIToolList
	(*AIToolDef)(nil),              // 13: kite.plugin.v1.AIToolDef
	(*AIToolRequest)(nil),          // 14: kite.plugin.v1.AIToolRequest
	(*AIToolResponse)(nil),         // 15: kite.plugin.v1.AIToolResponse
	(*AIToolAuthRequest)(nil),      // 16: kite.plugin.v1.AIToolAuthRequest
	(*AIToolAuthResponse)(nil),     // 17: kite.plugin.v1.AIToolAuthResponse
	(*ResourceHandlerList)(nil),    // 18: kite.plugin.v1.ResourceHandlerList
	(*ResourceHandlerDef)(nil),     // 19: kite.plugin.v1.ResourceHandlerDef
	(*ResourceRequest)(nil),        // 20: kite.plugin.v1.ResourceRequest
	(*ResourceResponse)(nil),       // 21: kite.plugin.v1.ResourceResponse
	(*MiddlewareConfig)(nil),       // 22: kite.plugin.v1.MiddlewareConfig
	(*MiddlewareRequest)(nil),      // 23: kite.plugin.v1.MiddlewareRequest
	(*MiddlewareResponse)(nil),     // 24: kite.plugin.v1.MiddlewareResponse
	(*ClusterEvent)(nil),           // 25: kite.plugin.v1.ClusterEvent
	nil,                            // 26: kite.plugin.v1.FrontendManifest.ExposedModulesEntry
	nil,                            // 27: kite.plugin.v1.HTTPRequest.HeadersEntry
	nil,                            // 28: kite.plugin.v1.HTTPRequest.QueryParamsEntry
	nil,                            // 29: kite.plugin.v1.HTTPResponse.HeadersEntry
	nil,                            // 30: kite.plugin.v1.ResourceRequest.QueryParamsEntry
	nil,                            // 31: kite.plugin.v1.MiddlewareRequest.HeadersEntry
	nil,                            // 32: kite.plugin.v1.MiddlewareResponse.ModifiedHeadersEntry
}
var file_pkg_plugin_proto_plugin_proto_depIdxs = []int32{
	3,  // 0: kite.plugin.v1.Manifest.requires:type_name -> kite.plugin.v1.Dependency
	4,  // 1: kite.plugin.v1.Manifest.permissions:type_name -> kite.plugin.v1.Permission
	5,  // 2: kite.plugin.v1.Manifest.frontend:type_name -> kite.plugin.v1.FrontendManifest
	8,  // 3: kite.plugin.v1.Manifest.settings:type_name -> kite.plugin.v1.SettingField
	26, // 4: kite.plugin.v1.FrontendManifest.exposed_modules:type_name -> kite.plugin.v1.FrontendManifest.ExposedModulesEntry
	6,  // 5: kite.plugin.v1.FrontendManifest.routes:type_name -> kite.plugin.v1.FrontendRoute
	7,  // 6: kite.plugin.v1.FrontendRoute.sidebar_entry:type_name -> kite.plugin.v1.SidebarEntry
	9,  // 7: kite.plugin.v1.SettingField.options:type_name -> kite.plugin.v1.SettingOption
	27, // 8: kite.plugin.v1.HTTPRequest.headers:type_name -> kite.plugin.v1.HTTPRequest.HeadersEntry
	28, // 9: kite.plugin.v1.HTTPRequest.query_params:type_name -> kite.plugin.v1.HTTPRequest.QueryParamsEntry
	29, // 10: kite.plugin.v1.HTTPResponse.headers:type_name -> kite.plugin.v1.HTTPResponse.HeadersEntry
	13, // 11: kite.plugin.v1.AIToolList.tools:type_name -> kite.plugin.v1.AIToolDef
	19, // 12: kite.plugin.v1.ResourceHandlerList.handlers:type_name -> kite.plugin.v1.ResourceHandlerDef
	30, // 13: kite.plugin.v1.ResourceRequest.query_params:type_name -> kite.plugin.v1.ResourceRequest.QueryParamsEntry
	31, // 14: kite.plugin.v1.MiddlewareRequest.headers:type_name -> kite.plugin.v1.MiddlewareRequest.HeadersEntry
	0,  // 15: kite.plugin.v1.MiddlewareResponse.action:type_name -> kite.plugin.v1.MiddlewareResponse.Action
	32, // 16: kite.plugin.v1.MiddlewareResponse.modified_headers:type_name -> kite.plugin.v1.MiddlewareResponse.ModifiedHeadersEntry
	1,  // 17: kite.plugin.v1.PluginService.GetManifest:input_type -> kite.plugin.v1.Empty
	1,  // 18: kite.plugin.v1.PluginService.Shutdown:input_type -> kite.plugin.v1.Empty
	25, // 19: kite.plugin.v1.PluginService.OnClusterEvent:input_type -> kite.plugin.v1.ClusterEvent
	10, // 20: kite.plugin.v1.PluginService.HandleHTTP:input_type -> kite.plugin.v1.HTTPRequest
	1,  // 21: kite.plugin.v1.PluginService.GetAITools:input_type -> kite.plugin.v1.Empty
	14, // 22: kite.plugin.v1.PluginService.ExecuteAITool:input_type -> kite.plugin.v1.AIToolRequest
	16, // 23: kite.plugin.v1.PluginService.AuthorizeAITool:input_type -> kite.plugin.v1.AIToolAuthRequest
	1,  // 24: kite.plugin.v1.PluginService.GetResourceHandlers:input_type -> kite.plugin.v1.Empty
	20, // 25: kite.plugin.v1.PluginService.HandleResource:input_type -> kite.plugin.v1.ResourceRequest
	1,  // 26: kite.plugin.v1.PluginService.GetMiddleware:input_type -> kite.plugin.v1.Empty
	23, // 27: kite.plugin.v1.PluginService.ApplyMiddleware:input_type -> kite.plugin.v1.MiddlewareRequest
	2,  // 28: kite.plugin.v1.PluginService.GetManifest:output_type -> kite.plugin.v1.Manifest
	1,  // 29: kite.plugin.v1.PluginService.Shutdown:output_type -> kite.plugin.v1.Empty
	1,  // 30: kite.plugin.v1.PluginService.OnClusterEvent:output_type -> kite.plugin.v1.Empty
	11, // 31: kite.plugin.v1.PluginService.HandleHTTP:output_type -> kite.plugin.v1.HTTPResponse
	12, // 32: kite.plugin.v1.PluginService.GetAITools:output_type -> kite.plugin.v1.AIToolList
	15, // 33: kite.plugin.v1.PluginService.ExecuteAITool:output_type -> kite.plugin.v1.AIToolResponse
	17, // 34: kite.plugin.v1.PluginService.AuthorizeAITool:output_type -> kite.plugin.v1.AIToolAuthResponse
	18, // 35: kite.plugin.v1.PluginService.GetResourceHandlers:output_type -> kite.plugin.v1.ResourceHandlerList
	21, // 36: kite.plugin.v1.PluginService.HandleResource:output_type -> kite.plugin.v1.ResourceResponse
	22, // 37: kite.plugin.v1.PluginService.GetMiddleware:output_type -> kite.plugin.v1.MiddlewareConfig
	24, // 38: kite.plugin.v1.PluginService.ApplyMiddleware:output_type -> kite.plugin.v1.MiddlewareResponse
	28, // [28:39] is the sub-list for method output_type
	17, // [17:28] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_pkg_plugin_proto_plugin_proto_init() }
func file_pkg_plugin_proto_plugin_proto_init() {
	if File_pkg_plugin_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_plugin_proto_rawDesc), len(file_pkg_plugin_proto_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugin_proto_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_plugin_proto_plugin_proto_depIdxs,
		EnumInfos:         file_pkg_plugin_proto_plugin_proto_enumTypes,
		MessageInfos:      file_pkg_plugin_proto_plugin_proto_msgTypes,
	}.Build()
	File_pkg_plugin_proto_plugin_proto = out.File
	file_pkg_plugin_proto_plugin_proto_goTypes = nil
	file_pkg_plugin_proto_plugin_proto_depIdxs = nil
}
