// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: pkg/plugin/proto/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_GetManifest_FullMethodName         = "/kite.plugin.v1.PluginService/GetManifest"
	PluginService_Shutdown_FullMethodName            = "/kite.plugin.v1.PluginService/Shutdown"
	PluginService_OnClusterEvent_FullMethodName      = "/kite.plugin.v1.PluginService/OnClusterEvent"
	PluginService_HandleHTTP_FullMethodName          = "/kite.plugin.v1.PluginService/HandleHTTP"
	PluginService_GetAITools_FullMethodName          = "/kite.plugin.v1.PluginService/GetAITools"
	PluginService_ExecuteAITool_FullMethodName       = "/kite.plugin.v1.PluginService/ExecuteAITool"
	PluginService_AuthorizeAITool_FullMethodName     = "/kite.plugin.v1.PluginService/AuthorizeAITool"
	PluginService_GetResourceHandlers_FullMethodName = "/kite.plugin.v1.PluginService/GetResourceHandlers"
	PluginService_HandleResource_FullMethodName      = "/kite.plugin.v1.PluginService/HandleResource"
	PluginService_GetMiddleware_FullMethodName       = "/kite.plugin.v1.PluginService/GetMiddleware"
	PluginService_ApplyMiddleware_FullMethodName     = "/kite.plugin.v1.PluginService/ApplyMiddleware"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginService is the main service that every Kite plugin process exposes.
// Kite connects to this service via HashiCorp go-plugin (gRPC over stdio).
type PluginServiceClient interface {
	// GetManifest returns the plugin's metadata, permissions, and frontend config.
	GetManifest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Manifest, error)
	// Shutdown tells the plugin to release resources and stop gracefully.
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// OnClusterEvent notifies the plugin of a cluster-level event.
	OnClusterEvent(ctx context.Context, in *ClusterEvent, opts ...grpc.CallOption) (*Empty, error)
	// HandleHTTP proxies an HTTP request from Kite to the plugin.
	// Used for custom routes registered by the plugin.
	HandleHTTP(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error)
	// GetAITools returns the list of AI tool definitions the plugin exposes.
	GetAITools(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AIToolList, error)
	// ExecuteAITool runs a specific AI tool with the given arguments.
	ExecuteAITool(ctx context.Context, in *AIToolRequest, opts ...grpc.CallOption) (*AIToolResponse, error)
	// AuthorizeAITool checks if a user has permission to invoke a tool.
	AuthorizeAITool(ctx context.Context, in *AIToolAuthRequest, opts ...grpc.CallOption) (*AIToolAuthResponse, error)
	// GetResourceHandlers returns the list of custom resource types
	// the plugin can handle (CRUD operations).
	GetResourceHandlers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResourceHandlerList, error)
	// HandleResource processes a CRUD operation on a plugin-managed resource.
	HandleResource(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error)
	// GetMiddleware returns the middleware configuration for this plugin.
	GetMiddleware(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MiddlewareConfig, error)
	// ApplyMiddleware processes a request through the plugin's middleware chain.
	ApplyMiddleware(ctx context.Context, in *MiddlewareRequest, opts ...grpc.CallOption) (*MiddlewareResponse, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) GetManifest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Manifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Manifest)
	err := c.cc.Invoke(ctx, PluginService_GetManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PluginService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) OnClusterEvent(ctx context.Context, in *ClusterEvent, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PluginService_OnClusterEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) HandleHTTP(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HTTPResponse)
	err := c.cc.Invoke(ctx, PluginService_HandleHTTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetAITools(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AIToolList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIToolList)
	err := c.cc.Invoke(ctx, PluginService_GetAITools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) ExecuteAITool(ctx context.Context, in *AIToolRequest, opts ...grpc.CallOption) (*AIToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIToolResponse)
	err := c.cc.Invoke(ctx, PluginService_ExecuteAITool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) AuthorizeAITool(ctx context.Context, in *AIToolAuthRequest, opts ...grpc.CallOption) (*AIToolAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIToolAuthResponse)
	err := c.cc.Invoke(ctx, PluginService_AuthorizeAITool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetResourceHandlers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResourceHandlerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceHandlerList)
	err := c.cc.Invoke(ctx, PluginService_GetResourceHandlers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) HandleResource(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceResponse)
	err := c.cc.Invoke(ctx, PluginService_HandleResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetMiddleware(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MiddlewareConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MiddlewareConfig)
	err := c.cc.Invoke(ctx, PluginService_GetMiddleware_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) ApplyMiddleware(ctx context.Context, in *MiddlewareRequest, opts ...grpc.CallOption) (*MiddlewareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MiddlewareResponse)
	err := c.cc.Invoke(ctx, PluginService_ApplyMiddleware_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
//
// PluginService is the main service that every Kite plugin process exposes.
// Kite connects to this service via HashiCorp go-plugin (gRPC over stdio).
type PluginServiceServer interface {
	// GetManifest returns the plugin's metadata, permissions, and frontend config.
	GetManifest(context.Context, *Empty) (*Manifest, error)
	// Shutdown tells the plugin to release resources and stop gracefully.
	Shutdown(context.Context, *Empty) (*Empty, error)
	// OnClusterEvent notifies the plugin of a cluster-level event.
	OnClusterEvent(context.Context, *ClusterEvent) (*Empty, error)
	// HandleHTTP proxies an HTTP request from Kite to the plugin.
	// Used for custom routes registered by the plugin.
	HandleHTTP(context.Context, *HTTPRequest) (*HTTPResponse, error)
	// GetAITools returns the list of AI tool definitions the plugin exposes.
	GetAITools(context.Context, *Empty) (*AIToolList, error)
	// ExecuteAITool runs a specific AI tool with the given arguments.
	ExecuteAITool(context.Context, *AIToolRequest) (*AIToolResponse, error)
	// AuthorizeAITool checks if a user has permission to invoke a tool.
	AuthorizeAITool(context.Context, *AIToolAuthRequest) (*AIToolAuthResponse, error)
	// GetResourceHandlers returns the list of custom resource types
	// the plugin can handle (CRUD operations).
	GetResourceHandlers(context.Context, *Empty) (*ResourceHandlerList, error)
	// HandleResource processes a CRUD operation on a plugin-managed resource.
	HandleResource(context.Context, *ResourceRequest) (*ResourceResponse, error)
	// GetMiddleware returns the middleware configuration for this plugin.
	GetMiddleware(context.Context, *Empty) (*MiddlewareConfig, error)
	// ApplyMiddleware processes a request through the plugin's middleware chain.
	ApplyMiddleware(context.Context, *MiddlewareRequest) (*MiddlewareResponse, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) GetManifest(context.Context, *Empty) (*Manifest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManifest not implemented")
}
func (UnimplementedPluginServiceServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedPluginServiceServer) OnClusterEvent(context.Context, *ClusterEvent) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnClusterEvent not implemented")
}
func (UnimplementedPluginServiceServer) HandleHTTP(context.Context, *HTTPRequest) (*HTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleHTTP not implemented")
}
func (UnimplementedPluginServiceServer) GetAITools(context.Context, *Empty) (*AIToolList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAITools not implemented")
}
func (UnimplementedPluginServiceServer) ExecuteAITool(context.Context, *AIToolRequest) (*AIToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteAITool not implemented")
}
func (UnimplementedPluginServiceServer) AuthorizeAITool(context.Context, *AIToolAuthRequest) (*AIToolAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthorizeAITool not implemented")
}
func (UnimplementedPluginServiceServer) GetResourceHandlers(context.Context, *Empty) (*ResourceHandlerList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResourceHandlers not implemented")
}
func (UnimplementedPluginServiceServer) HandleResource(context.Context, *ResourceRequest) (*ResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleResource not implemented")
}
func (UnimplementedPluginServiceServer) GetMiddleware(context.Context, *Empty) (*MiddlewareConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMiddleware not implemented")
}
func (UnimplementedPluginServiceServer) ApplyMiddleware(context.Context, *MiddlewareRequest) (*MiddlewareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyMiddleware not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_GetManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetManifest(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_OnClusterEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).OnClusterEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_OnClusterEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).OnClusterEvent(ctx, req.(*ClusterEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_HandleHTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).HandleHTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_HandleHTTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).HandleHTTP(ctx, req.(*HTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetAITools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetAITools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetAITools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetAITools(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_ExecuteAITool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).ExecuteAITool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_ExecuteAITool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).ExecuteAITool(ctx, req.(*AIToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_AuthorizeAITool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIToolAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).AuthorizeAITool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_AuthorizeAITool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).AuthorizeAITool(ctx, req.(*AIToolAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetResourceHandlers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetResourceHandlers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetResourceHandlers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetResourceHandlers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_HandleResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).HandleResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_HandleResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).HandleResource(ctx, req.(*ResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetMiddleware_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetMiddleware(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetMiddleware_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetMiddleware(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_ApplyMiddleware_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MiddlewareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).ApplyMiddleware(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_ApplyMiddleware_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).ApplyMiddleware(ctx, req.(*MiddlewareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kite.plugin.v1.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManifest",
			Handler:    _PluginService_GetManifest_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _PluginService_Shutdown_Handler,
		},
		{
			MethodName: "OnClusterEvent",
			Handler:    _PluginService_OnClusterEvent_Handler,
		},
		{
			MethodName: "HandleHTTP",
			Handler:    _PluginService_HandleHTTP_Handler,
		},
		{
			MethodName: "GetAITools",
			Handler:    _PluginService_GetAITools_Handler,
		},
		{
			MethodName: "ExecuteAITool",
			Handler:    _PluginService_ExecuteAITool_Handler,
		},
		{
			MethodName: "AuthorizeAITool",
			Handler:    _PluginService_AuthorizeAITool_Handler,
		},
		{
			MethodName: "GetResourceHandlers",
			Handler:    _PluginService_GetResourceHandlers_Handler,
		},
		{
			MethodName: "HandleResource",
			Handler:    _PluginService_HandleResource_Handler,
		},
		{
			MethodName: "GetMiddleware",
			Handler:    _PluginService_GetMiddleware_Handler,
		},
		{
			MethodName: "ApplyMiddleware",
			Handler:    _PluginService_ApplyMiddleware_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugin/proto/plugin.proto",
}
